BOUNDARY_HINT_REGISTRY = {
    "browser_boundary": {
        "domains": {"sw", "cn"},
        "tags": {"cors", "reactjs", "javascript", "typescript", "http", "authentication", "authorization"},
        "keywords": {"browser", "frontend", "origin", "cookie", "cookies", "session", "csrf", "preflight", "credentials"},
        "phrases": {"access-control", "cross origin", "cross-origin", "credentials mode"},
    },
    "proxy_boundary": {
        "domains": {"sw", "cn", "ai"},
        "tags": {"proxy", "reverse-proxy", "nginx", "apache", "ingress", "load-balancing", "http"},
        "keywords": {"proxy", "upstream", "forwarded", "gateway", "ingress", "lb", "header"},
        "phrases": {"reverse proxy", "x-forwarded", "load balancer", "moved behind proxy"},
    },
    "runtime_boundary": {
        "domains": {"sw", "ai"},
        "tags": {"python", "java", "node.js", "debugging", "logging", "fastapi", "django", "flask", "express", "spring-boot", "asp.net-core"},
        "keywords": {"runtime", "worker", "process", "startup", "dependency", "environment", "config", "version", "secret"},
        "phrases": {"virtual environment", "runtime config", "env var", "environment variable"},
    },
    "database_boundary": {
        "domains": {"sw", "ai"},
        "tags": {"sql", "postgresql", "mysql", "redis", "vector-database"},
        "keywords": {"database", "db", "dsn", "connection", "query", "migration", "cache", "pool"},
        "phrases": {"connection string", "database connection"},
    },
    "network_transport_boundary": {
        "domains": {"sw", "cn", "ai"},
        "tags": {"networking", "dns", "ssl", "tls", "tcp", "http", "firewall", "routing", "vpn", "proxy", "reverse-proxy"},
        "keywords": {"socket", "resolve", "resolver", "latency", "handshake", "timeout", "hostname", "connectivity"},
        "phrases": {"dns lookup", "tls handshake", "connection reset", "connection timed out"},
    },
    "model_serving_boundary": {
        "domains": {"ai"},
        "tags": {"model-serving", "large-language-model", "huggingface-transformers", "sentence-transformers", "embeddings", "rag", "vector-database", "inference"},
        "keywords": {"tokenizer", "serving", "endpoint", "generation", "embedding", "retrieval", "prompt", "model"},
        "phrases": {"model endpoint", "serving stack", "inference endpoint", "vector store"},
    },
    "gpu_inference_boundary": {
        "domains": {"ai"},
        "tags": {"gpu", "cuda", "inference", "pytorch", "tensorflow"},
        "keywords": {"gpu", "cuda", "nvidia", "vram", "oom", "throughput", "latency"},
        "phrases": {"out of memory", "cuda error", "gpu memory"},
    },
    "deployment_change_hint": {
        "domains": {"sw", "cn", "ai"},
        "tags": {"docker", "kubernetes", "ingress", "mlops", "debugging"},
        "keywords": {"deploy", "deployment", "release", "upgrade", "rollback", "migrate", "restart", "rollout"},
        "phrases": {"after deploy", "after deployment", "after upgrade", "after update", "after moving behind proxy", "after enabling", "after restart", "after migration"},
    },
}

CLUSTER_REGISTRY = {
    "auth_identity_flow": {
        "title": "Authentication and identity flow",
        "domains": {"sw"},
        "tags": {"authentication", "authorization", "jwt", "oauth-2.0", "fastapi", "django", "flask", "express", "spring-boot", "asp.net-core"},
        "keywords": {"auth", "login", "token", "session", "scope", "role", "permission", "bearer"},
        "phrases": {"access token", "refresh token", "unauthorized", "forbidden"},
        "boundaries": {"browser_boundary", "proxy_boundary", "runtime_boundary"},
        "issue_families": {"authentication": 1.0, "authorization_policy": 0.72, "session_identity_boundary": 0.58},
    },
    "http_proxy_edge": {
        "title": "HTTP, proxy, and edge handling",
        "domains": {"sw", "cn"},
        "tags": {"http", "cors", "proxy", "reverse-proxy", "nginx", "apache", "ingress", "load-balancing", "rest"},
        "keywords": {"origin", "upstream", "gateway", "header", "redirect", "route", "preflight"},
        "phrases": {"reverse proxy", "x-forwarded", "access-control", "bad gateway"},
        "boundaries": {"browser_boundary", "proxy_boundary", "network_transport_boundary"},
        "issue_families": {"cors_proxy_boundary": 1.0, "http_routing_misconfiguration": 0.86, "authentication": 0.28},
    },
    "database_connectivity_stack": {
        "title": "Database connectivity and runtime target",
        "domains": {"sw", "ai"},
        "tags": {"sql", "postgresql", "mysql", "redis", "vector-database"},
        "keywords": {"database", "db", "query", "connection", "pool", "migration", "hostname", "port", "credential"},
        "phrases": {"connection string", "database timeout"},
        "boundaries": {"database_boundary", "runtime_boundary"},
        "issue_families": {"database_connectivity": 1.0, "cache_session_store": 0.52, "retrieval_embeddings_pipeline": 0.28},
    },
    "container_network_surface": {
        "title": "Container and service-network surface",
        "domains": {"cn", "sw", "ai"},
        "tags": {"docker", "kubernetes", "ingress", "load-balancing", "routing", "firewall", "networking", "dns", "proxy"},
        "keywords": {"pod", "service", "cluster", "namespace", "nodeport", "mesh", "policy"},
        "phrases": {"network policy", "service mesh", "container network"},
        "boundaries": {"proxy_boundary", "network_transport_boundary", "deployment_change_hint"},
        "issue_families": {"container_networking": 1.0, "dns_service_discovery": 0.78, "http_routing_misconfiguration": 0.44},
    },
    "tls_dns_transport": {
        "title": "DNS and transport security",
        "domains": {"cn", "sw", "ai"},
        "tags": {"dns", "ssl", "tls", "tcp", "http", "networking", "routing"},
        "keywords": {"resolver", "certificate", "handshake", "host", "port", "timeout"},
        "phrases": {"tls handshake", "dns lookup", "certificate verify failed"},
        "boundaries": {"network_transport_boundary", "proxy_boundary"},
        "issue_families": {"dns_service_discovery": 1.0, "tls_edge_termination": 0.88, "http_routing_misconfiguration": 0.5},
    },
    "model_serving_pipeline": {
        "title": "Model serving and inference pipeline",
        "domains": {"ai"},
        "tags": {"model-serving", "large-language-model", "inference", "huggingface-transformers", "sentence-transformers", "rag", "embeddings", "vector-database"},
        "keywords": {"tokenizer", "generation", "retrieval", "embedding", "latency", "endpoint"},
        "phrases": {"model endpoint", "serving stack", "retrieval augmented"},
        "boundaries": {"model_serving_boundary", "gpu_inference_boundary", "database_boundary"},
        "issue_families": {"model_serving_runtime": 1.0, "retrieval_embeddings_pipeline": 0.86, "gpu_inference_runtime": 0.55},
    },
    "gpu_acceleration_stack": {
        "title": "GPU acceleration and execution runtime",
        "domains": {"ai"},
        "tags": {"gpu", "cuda", "pytorch", "tensorflow", "inference"},
        "keywords": {"vram", "nvidia", "throughput", "latency", "memory"},
        "phrases": {"out of memory", "cuda error", "gpu memory"},
        "boundaries": {"gpu_inference_boundary", "runtime_boundary"},
        "issue_families": {"gpu_inference_runtime": 1.0, "model_serving_runtime": 0.5},
    },
}

ISSUE_FAMILY_REGISTRY = {
    "authentication": {
        "domains": {"sw"},
        "tags": {"authentication", "authorization", "jwt", "oauth-2.0", "fastapi", "django", "flask"},
        "keywords": {"auth", "token", "session", "login", "issuer", "audience", "signature"},
        "phrases": {"unauthorized", "invalid token", "missing token", "token expired"},
        "clusters": {"auth_identity_flow": 1.0, "http_proxy_edge": 0.25},
        "boundaries": {"browser_boundary": 0.24, "proxy_boundary": 0.16, "runtime_boundary": 0.14},
        "anti_tags": {"dns", "tls", "cuda"},
    },
    "authorization_policy": {
        "domains": {"sw"},
        "tags": {"authorization", "jwt", "oauth-2.0", "authentication"},
        "keywords": {"scope", "role", "permission", "claims", "policy", "decision"},
        "phrases": {"access denied", "insufficient scope", "permission denied"},
        "clusters": {"auth_identity_flow": 0.92},
        "boundaries": {"browser_boundary": 0.12, "runtime_boundary": 0.12},
        "anti_tags": {"dns", "gpu"},
    },
    "session_identity_boundary": {
        "domains": {"sw"},
        "tags": {"authentication", "authorization", "cors", "reactjs", "fastapi", "django"},
        "keywords": {"cookie", "session", "csrf", "browser", "credentials"},
        "phrases": {"same site", "same-site", "credentials include"},
        "clusters": {"auth_identity_flow": 0.66, "http_proxy_edge": 0.5},
        "boundaries": {"browser_boundary": 0.28, "proxy_boundary": 0.1},
        "anti_tags": {"gpu", "cuda"},
    },
    "cors_proxy_boundary": {
        "domains": {"sw", "cn"},
        "tags": {"cors", "http", "proxy", "reverse-proxy", "nginx", "apache", "ingress", "reactjs"},
        "keywords": {"origin", "preflight", "headers", "browser", "gateway"},
        "phrases": {"access-control", "preflight request", "cross-origin"},
        "clusters": {"http_proxy_edge": 1.0},
        "boundaries": {"browser_boundary": 0.26, "proxy_boundary": 0.22, "network_transport_boundary": 0.1},
        "anti_tags": {"cuda", "gpu"},
    },
    "http_routing_misconfiguration": {
        "domains": {"sw", "cn"},
        "tags": {"http", "rest", "proxy", "reverse-proxy", "routing", "ingress", "load-balancing", "nginx", "apache"},
        "keywords": {"path", "route", "upstream", "gateway", "endpoint", "rewrite"},
        "phrases": {"bad gateway", "service unavailable", "route mismatch"},
        "clusters": {"http_proxy_edge": 0.84, "container_network_surface": 0.35, "tls_dns_transport": 0.24},
        "boundaries": {"proxy_boundary": 0.22, "network_transport_boundary": 0.16},
        "anti_tags": {"gpu", "jwt"},
    },
    "database_connectivity": {
        "domains": {"sw", "ai"},
        "tags": {"sql", "postgresql", "mysql", "redis", "python", "fastapi", "django"},
        "keywords": {"database", "connection", "pool", "query", "dsn", "hostname", "port", "credential"},
        "phrases": {"connection refused", "database timeout", "connection string"},
        "clusters": {"database_connectivity_stack": 1.0},
        "boundaries": {"database_boundary": 0.3, "runtime_boundary": 0.1},
        "anti_tags": {"cuda", "tls"},
    },
    "cache_session_store": {
        "domains": {"sw"},
        "tags": {"redis", "authentication", "authorization"},
        "keywords": {"session", "cache", "token", "state"},
        "phrases": {"session store", "cache miss"},
        "clusters": {"database_connectivity_stack": 0.68, "auth_identity_flow": 0.32},
        "boundaries": {"database_boundary": 0.18, "runtime_boundary": 0.12},
        "anti_tags": {"cuda"},
    },
    "container_networking": {
        "domains": {"cn", "sw", "ai"},
        "tags": {"docker", "kubernetes", "networking", "ingress", "routing", "proxy", "firewall"},
        "keywords": {"pod", "service", "namespace", "mesh", "policy", "container"},
        "phrases": {"network policy", "service mesh", "container network"},
        "clusters": {"container_network_surface": 1.0},
        "boundaries": {"network_transport_boundary": 0.18, "proxy_boundary": 0.12, "deployment_change_hint": 0.1},
        "anti_tags": {"jwt", "oauth-2.0"},
    },
    "dns_service_discovery": {
        "domains": {"cn", "sw", "ai"},
        "tags": {"dns", "networking", "kubernetes", "docker", "routing", "proxy"},
        "keywords": {"resolve", "resolver", "host", "hostname", "service", "ttl"},
        "phrases": {"dns lookup", "name resolution", "service discovery"},
        "clusters": {"tls_dns_transport": 0.8, "container_network_surface": 0.46},
        "boundaries": {"network_transport_boundary": 0.26, "deployment_change_hint": 0.08},
        "anti_tags": {"jwt", "gpu"},
    },
    "tls_edge_termination": {
        "domains": {"cn", "sw"},
        "tags": {"ssl", "tls", "nginx", "apache", "proxy", "http"},
        "keywords": {"certificate", "handshake", "https", "cipher", "sni"},
        "phrases": {"tls handshake", "certificate verify failed", "ssl error"},
        "clusters": {"tls_dns_transport": 0.92, "http_proxy_edge": 0.32},
        "boundaries": {"network_transport_boundary": 0.28, "proxy_boundary": 0.18},
        "anti_tags": {"gpu", "redis"},
    },
    "model_serving_runtime": {
        "domains": {"ai"},
        "tags": {"model-serving", "large-language-model", "inference", "huggingface-transformers", "sentence-transformers", "mlops"},
        "keywords": {"tokenizer", "endpoint", "latency", "generation", "model"},
        "phrases": {"model endpoint", "serving stack", "inference endpoint"},
        "clusters": {"model_serving_pipeline": 1.0, "gpu_acceleration_stack": 0.2},
        "boundaries": {"model_serving_boundary": 0.32, "runtime_boundary": 0.1},
        "anti_tags": {"dns"},
    },
    "retrieval_embeddings_pipeline": {
        "domains": {"ai"},
        "tags": {"rag", "embeddings", "vector-database", "sentence-transformers", "nlp", "model-serving"},
        "keywords": {"retrieval", "embedding", "vector", "index", "chunk", "search"},
        "phrases": {"vector store", "embedding model", "retrieval pipeline"},
        "clusters": {"model_serving_pipeline": 0.82, "database_connectivity_stack": 0.34},
        "boundaries": {"model_serving_boundary": 0.2, "database_boundary": 0.16},
        "anti_tags": {"tls"},
    },
    "gpu_inference_runtime": {
        "domains": {"ai"},
        "tags": {"gpu", "cuda", "inference", "pytorch", "tensorflow"},
        "keywords": {"gpu", "cuda", "vram", "memory", "nvidia", "latency"},
        "phrases": {"out of memory", "cuda error", "gpu memory"},
        "clusters": {"gpu_acceleration_stack": 1.0, "model_serving_pipeline": 0.25},
        "boundaries": {"gpu_inference_boundary": 0.34, "runtime_boundary": 0.08},
        "anti_tags": {"dns", "oauth-2.0"},
    },
}

__all__ = [
    "BOUNDARY_HINT_REGISTRY",
    "CLUSTER_REGISTRY",
    "ISSUE_FAMILY_REGISTRY",
]
