BOUNDARY_LABELS = {
    "browser_boundary": "browser-to-backend boundary",
    "proxy_boundary": "proxy or ingress boundary",
    "runtime_boundary": "runtime configuration boundary",
    "database_boundary": "database access boundary",
    "network_transport_boundary": "network transport boundary",
    "model_serving_boundary": "model serving boundary",
    "gpu_inference_boundary": "GPU inference boundary",
    "deployment_change_hint": "deployment change boundary",
}

ISSUE_FAMILY_COMPATIBILITY_MAP = {
    "authentication": "authentication",
    "authorization_policy": "authentication",
    "session_identity_boundary": "authentication",
    "cors_proxy_boundary": "cors",
    "http_routing_misconfiguration": "reverse_proxy",
    "database_connectivity": "database_connectivity",
    "cache_session_store": "database_connectivity",
    "container_networking": "networking_path",
    "dns_service_discovery": "dns_resolution",
    "tls_edge_termination": "ssl_tls",
    "model_serving_runtime": "inference_runtime",
    "retrieval_embeddings_pipeline": "inference_runtime",
    "gpu_inference_runtime": "resource_exhaustion",
}

TAG_CATEGORY_RULES = {
    "auth": {"authentication", "authorization", "jwt", "oauth-2.0"},
    "web_framework": {"fastapi", "django", "flask", "express", "spring-boot", "asp.net-core"},
    "frontend": {"reactjs", "javascript", "typescript", "html", "css"},
    "proxy_edge": {"http", "rest", "proxy", "reverse-proxy", "nginx", "apache", "ingress", "load-balancing"},
    "network": {"networking", "dns", "ssl", "tls", "tcp", "routing", "firewall", "vpn", "ssh"},
    "infra": {"docker", "kubernetes", "linux", "ubuntu", "azure", "bash"},
    "database": {"sql", "postgresql", "mysql", "redis", "vector-database"},
    "runtime": {"python", "java", "node.js", "debugging", "logging", "git"},
    "ml_framework": {"machine-learning", "deep-learning", "tensorflow", "pytorch", "scikit-learn", "opencv", "numpy", "pandas", "computer-vision", "nlp", "fine-tuning"},
    "ai_serving": {"large-language-model", "model-serving", "inference", "embeddings", "rag", "huggingface-transformers", "sentence-transformers", "mlops"},
    "gpu_compute": {"gpu", "cuda"},
}

MAJOR_TAGS = {
    "fastapi", "jwt", "cors", "nginx", "proxy", "kubernetes", "docker", "dns",
    "postgresql", "mysql", "redis", "pytorch", "cuda", "gpu", "inference",
    "embeddings", "rag", "model-serving", "authentication", "authorization",
}

ROOT_CAUSE_STACK_GROUPS = {
    "backend_web_framework": {"django", "fastapi", "flask", "express", "spring-boot", "asp.net-core"},
    "backing_store": {"postgresql", "mysql", "redis", "vector-database", "sql"},
    "proxy_server": {"nginx", "apache", "proxy", "reverse-proxy", "ingress", "load-balancing"},
    "auth_protocol": {"jwt", "oauth-2.0", "authentication", "authorization"},
    "model_runtime": {"model-serving", "large-language-model", "huggingface-transformers", "sentence-transformers", "embeddings", "rag", "inference"},
    "gpu_runtime": {"gpu", "cuda", "pytorch", "tensorflow"},
}

FAMILY_ALTERNATIVE_PATHS = {
    "authentication": [
        "Confirm auth headers and cookies arrive unchanged at the backend validator",
        "Confirm browser credential mode and cookie scope match backend auth expectations",
        "Confirm the authenticated identity maps to the route's required role and scope",
    ],
    "authorization_policy": [
        "Map the denied request to the exact policy rule and required scope set",
        "Confirm middleware or proxy rewrites do not alter protected route context",
        "Confirm policy cache and session state are fresh for the evaluated identity",
    ],
    "session_identity_boundary": [
        "Confirm SameSite, CSRF token flow, and credential mode preserve session continuity",
        "Confirm proxy forwarding preserves secure cookie scope and attributes",
        "Confirm client and backend use the same auth mechanism on the failing route",
    ],
    "cors_proxy_boundary": [
        "Confirm the backend allowlist explicitly covers failing origin, method, and headers",
        "Confirm ingress or proxy forwarding does not alter visible origin and request headers",
        "Confirm credentialed browser flow matches the successful server-to-server path",
    ],
    "http_routing_misconfiguration": [
        "Confirm upstream target, host preservation, and route rewrite resolve to the intended service",
        "Confirm recent deployment did not change path, host, or ingress mapping",
        "Confirm edge timeout behavior is not masking the primary upstream failure hop",
    ],
    "database_connectivity": [
        "Confirm runtime DSN, host, port, and secret resolve to the intended database target",
        "Confirm service discovery and policy allow the runtime-to-database network hop",
        "Confirm connection pool saturation is not producing intermittent data-path failures",
    ],
    "cache_session_store": [
        "Confirm Redis or cache-backed session records are current and fully written",
        "Confirm cache topology supports the state continuity expected by the application",
        "Confirm failover or restart events did not break the live auth or cache contract",
    ],
    "container_networking": [
        "Confirm service selectors, ports, and network policy match the deployed workload",
        "Confirm ingress, mesh, and load-balancer behavior matches direct service routing",
        "Confirm DNS and endpoint registration are current for the active rollout",
    ],
    "dns_service_discovery": [
        "Confirm the caller resolves the expected hostname and search domain",
        "Confirm cluster DNS and resolver policy return consistent answers across replicas",
        "Confirm downstream transport failures are not caused by initial name-resolution drift",
    ],
    "tls_edge_termination": [
        "Confirm certificate trust chain, hostname, and SNI handling are correct at the edge",
        "Confirm ingress termination mode matches backend TLS expectations",
        "Confirm proxy forwarding does not hide the true certificate or handshake failure point",
    ],
    "model_serving_runtime": [
        "Confirm model artifacts, tokenizer assets, and runtime precision are aligned",
        "Confirm deployment or environment drift did not change serving startup behavior",
        "Confirm request size and concurrency do not force fallback to a degraded serving path",
    ],
    "retrieval_embeddings_pipeline": [
        "Confirm embedding generation and vector lookup use the same model and index contract",
        "Confirm retrieval latency and vector-store access are not masking serving failures",
        "Confirm ingestion and chunking changes did not break retrieval assumptions",
    ],
    "gpu_inference_runtime": [
        "Confirm accelerator runtime capacity matches current batch shape and concurrency",
        "Confirm CUDA, driver, and framework versions are compatible on the serving node",
        "Confirm workload does not switch unexpectedly between CPU and GPU execution paths",
    ],
}

TAG_CONTEXT_OVERRIDES = {
    "jwt": "JWT validation flow",
    "oauth-2.0": "OAuth 2.0 identity flow",
    "fastapi": "FastAPI request pipeline",
    "django": "Django request and session flow",
    "reactjs": "React browser request flow",
    "nginx": "Nginx edge proxy path",
    "reverse-proxy": "reverse proxy forwarding path",
    "postgresql": "PostgreSQL access path",
    "mysql": "MySQL access path",
    "redis": "Redis state path",
    "docker": "container runtime path",
    "kubernetes": "Kubernetes service path",
    "vector-database": "vector-store access path",
    "large-language-model": "LLM serving path",
    "model-serving": "model serving path",
    "sentence-transformers": "sentence-transformer pipeline",
    "huggingface-transformers": "Transformers model runtime",
    "gpu": "GPU execution path",
    "cuda": "CUDA execution path",
}

SCENARIO_LIBRARY = {
    "config_alignment": {
        "categories": {"auth", "web_framework", "runtime", "database", "ai_serving", "ml_framework"},
        "families": {"authentication", "database_connectivity", "model_serving_runtime", "gpu_inference_runtime"},
        "boundaries": {"runtime_boundary", "deployment_change_hint", "database_boundary", "model_serving_boundary"},
        "symptoms": {"config", "availability", "deployment", "ai_runtime"},
        "path_template": "Validate {tag_context} configuration alignment across the {boundary_label}",
        "cause_template": "{tag_context} configuration does not match the live {boundary_label}, so the runtime is using the wrong secret, endpoint, mode, or environment value",
        "base_weight": 1.0,
    },
    "boundary_propagation": {
        "categories": {"auth", "frontend", "proxy_edge", "web_framework"},
        "families": {"authentication", "session_identity_boundary", "cors_proxy_boundary", "authorization_policy"},
        "boundaries": {"browser_boundary", "proxy_boundary", "runtime_boundary"},
        "symptoms": {"auth", "boundary", "availability"},
        "path_template": "Trace {tag_context} propagation across the {boundary_label}",
        "cause_template": "{tag_context} is not crossing the {boundary_label} intact, so headers, cookies, or request metadata diverge before the service evaluates the request",
        "base_weight": 1.12,
    },
    "policy_evaluation": {
        "categories": {"auth", "web_framework", "frontend"},
        "families": {"authorization_policy", "authentication", "session_identity_boundary"},
        "boundaries": {"browser_boundary", "runtime_boundary", "proxy_boundary"},
        "symptoms": {"auth", "config"},
        "path_template": "Inspect policy evaluation and identity state around the {boundary_label}",
        "cause_template": "Policy evaluation around the {boundary_label} does not match the authenticated identity, so roles, scopes, or session state block the intended operation",
        "base_weight": 1.05,
    },
    "proxy_forwarding": {
        "categories": {"proxy_edge", "network", "infra", "frontend"},
        "families": {"cors_proxy_boundary", "http_routing_misconfiguration", "tls_edge_termination", "authentication"},
        "boundaries": {"proxy_boundary", "browser_boundary", "network_transport_boundary"},
        "symptoms": {"boundary", "availability", "timeout", "tls"},
        "path_template": "Inspect forwarding, rewrites, and upstream behavior at the {boundary_label}",
        "cause_template": "Forwarding behavior at the {boundary_label} is rewriting headers, paths, hosts, or upstream targeting in a way that breaks the live request path",
        "base_weight": 1.14,
    },
    "transport_resolution": {
        "categories": {"network", "proxy_edge", "infra"},
        "families": {"dns_service_discovery", "tls_edge_termination", "container_networking", "http_routing_misconfiguration"},
        "boundaries": {"network_transport_boundary", "proxy_boundary", "deployment_change_hint"},
        "symptoms": {"connectivity", "tls", "timeout", "availability"},
        "path_template": "Validate resolution, routing, and transport behavior across the {boundary_label}",
        "cause_template": "Resolution or transport handling at the {boundary_label} is misaligned with the target path, so the caller reaches the wrong hop or cannot complete the connection",
        "base_weight": 1.13,
    },
    "service_availability": {
        "categories": {"infra", "proxy_edge", "ai_serving", "runtime"},
        "families": {"http_routing_misconfiguration", "container_networking", "model_serving_runtime"},
        "boundaries": {"deployment_change_hint", "proxy_boundary", "runtime_boundary", "model_serving_boundary"},
        "symptoms": {"availability", "timeout", "deployment"},
        "path_template": "Verify service availability, readiness, and target health across the {boundary_label}",
        "cause_template": "The service behind the {boundary_label} is unhealthy, restarting, or targeted incorrectly, so callers see an availability failure before the intended work completes",
        "base_weight": 1.1,
    },
    "runtime_dependency": {
        "categories": {"runtime", "web_framework", "ml_framework", "gpu_compute", "ai_serving"},
        "families": {"model_serving_runtime", "gpu_inference_runtime", "database_connectivity"},
        "boundaries": {"runtime_boundary", "model_serving_boundary", "deployment_change_hint"},
        "symptoms": {"config", "ai_runtime", "deployment"},
        "path_template": "Check runtime dependencies and execution assumptions across the {boundary_label}",
        "cause_template": "A runtime dependency or execution assumption tied to the {boundary_label} no longer matches the deployed code path or serving environment",
        "base_weight": 1.02,
    },
    "state_store_integrity": {
        "categories": {"database", "auth", "web_framework", "infra"},
        "families": {"cache_session_store", "database_connectivity", "session_identity_boundary"},
        "boundaries": {"database_boundary", "runtime_boundary", "deployment_change_hint"},
        "symptoms": {"auth", "data", "availability"},
        "path_template": "Validate state storage, persistence, and consistency across the {boundary_label}",
        "cause_template": "State handled through the {boundary_label} is stale, missing, or partially written, so the runtime reads inconsistent session, cache, or backing-store data",
        "base_weight": 0.98,
    },
    "schema_contract": {
        "categories": {"database", "runtime", "ai_serving"},
        "families": {"database_connectivity", "retrieval_embeddings_pipeline"},
        "boundaries": {"database_boundary", "runtime_boundary", "model_serving_boundary"},
        "symptoms": {"data", "config", "availability"},
        "path_template": "Confirm data contract, schema, and request-shape assumptions across the {boundary_label}",
        "cause_template": "The contract enforced at the {boundary_label} no longer matches the live schema, index shape, or request payload expectations",
        "base_weight": 1.0,
    },
    "latency_budget": {
        "categories": {"network", "proxy_edge", "ai_serving", "gpu_compute", "infra"},
        "families": {"http_routing_misconfiguration", "model_serving_runtime", "gpu_inference_runtime", "container_networking"},
        "boundaries": {"network_transport_boundary", "proxy_boundary", "gpu_inference_boundary", "model_serving_boundary"},
        "symptoms": {"timeout", "availability", "ai_runtime"},
        "path_template": "Measure latency budget and timeout behavior across the {boundary_label}",
        "cause_template": "Latency introduced at the {boundary_label} exceeds the active timeout or retry budget, so the request fails before the downstream work finishes",
        "base_weight": 1.08,
    },
    "artifact_loading": {
        "categories": {"ai_serving", "ml_framework", "gpu_compute"},
        "families": {"model_serving_runtime", "retrieval_embeddings_pipeline", "gpu_inference_runtime"},
        "boundaries": {"model_serving_boundary", "runtime_boundary", "deployment_change_hint"},
        "symptoms": {"ai_runtime", "deployment", "config"},
        "path_template": "Validate model artifacts, runtime assets, and loading assumptions across the {boundary_label}",
        "cause_template": "Artifacts or runtime assets tied to the {boundary_label} are missing, mismatched, or loaded in an incompatible mode for the active request path",
        "base_weight": 1.1,
    },
    "capacity_exhaustion": {
        "categories": {"gpu_compute", "ai_serving", "runtime", "database", "infra"},
        "families": {"gpu_inference_runtime", "model_serving_runtime", "database_connectivity", "container_networking"},
        "boundaries": {"gpu_inference_boundary", "runtime_boundary", "database_boundary", "model_serving_boundary"},
        "symptoms": {"timeout", "availability", "ai_runtime"},
        "path_template": "Check resource pressure and execution capacity across the {boundary_label}",
        "cause_template": "Resource pressure at the {boundary_label} is forcing the runtime into retries, throttling, memory exhaustion, or degraded execution behavior",
        "base_weight": 1.06,
    },
    "deployment_regression": {
        "categories": {"infra", "runtime", "web_framework", "ai_serving", "proxy_edge"},
        "families": {"authentication", "http_routing_misconfiguration", "container_networking", "model_serving_runtime", "gpu_inference_runtime"},
        "boundaries": {"deployment_change_hint", "runtime_boundary", "proxy_boundary"},
        "symptoms": {"deployment", "config", "availability"},
        "path_template": "Compare pre-change and post-change behavior around the {boundary_label}",
        "cause_template": "A recent deployment or environment change around the {boundary_label} shifted the live path, dependency set, or runtime configuration away from the previously working state",
        "base_weight": 1.04,
    },
    "retrieval_pipeline": {
        "categories": {"ai_serving", "database", "ml_framework"},
        "families": {"retrieval_embeddings_pipeline", "model_serving_runtime", "database_connectivity"},
        "boundaries": {"model_serving_boundary", "database_boundary", "runtime_boundary"},
        "symptoms": {"ai_runtime", "data", "timeout"},
        "path_template": "Trace retrieval, embedding generation, and vector lookup across the {boundary_label}",
        "cause_template": "The retrieval path coordinated through the {boundary_label} is inconsistent, so embeddings, vector lookups, or downstream model assumptions no longer align",
        "base_weight": 1.12,
    },
    "tensor_shape_validation": {
        "categories": {"ml_framework", "gpu_compute", "ai_serving", "runtime"},
        "families": {"gpu_inference_runtime", "model_serving_runtime"},
        "boundaries": {"gpu_inference_boundary", "runtime_boundary", "model_serving_boundary"},
        "symptoms": {"ai_runtime", "config"},
        "path_template": "Validate tensor shape and feature-dimension alignment across the {boundary_label}",
        "cause_template": "The tensor shape or feature dimension entering the model through the {boundary_label} does not match what the model layer expects, so matrix multiplication or broadcasting fails",
        "base_weight": 1.16,
    },
}

__all__ = [
    "BOUNDARY_LABELS",
    "ISSUE_FAMILY_COMPATIBILITY_MAP",
    "TAG_CATEGORY_RULES",
    "MAJOR_TAGS",
    "ROOT_CAUSE_STACK_GROUPS",
    "FAMILY_ALTERNATIVE_PATHS",
    "TAG_CONTEXT_OVERRIDES",
    "SCENARIO_LIBRARY",
]
