from app.repositories.tags import AI_TAGS, NETWORK_TAGS, SOFTWARE_TAGS

DOMAIN_TAGS = {
    "software": SOFTWARE_TAGS,
    "networking": NETWORK_TAGS,
    "ai": AI_TAGS,
}

PHASE_ORDER = [
    "capture_baseline",
    "boundary_verification",
    "primary_hypothesis_test",
    "secondary_branch_test",
    "runtime_config_confirmation",
    "retest_and_closure",
]

BOUNDARY_LABELS = {
    "browser_boundary": "browser-to-backend boundary",
    "proxy_boundary": "proxy or ingress boundary",
    "runtime_boundary": "runtime configuration boundary",
    "database_boundary": "database access boundary",
    "network_transport_boundary": "network transport boundary",
    "model_serving_boundary": "model serving boundary",
    "gpu_inference_boundary": "GPU inference boundary",
    "deployment_change_hint": "deployment change boundary",
}

FAMILY_STEP_SEQUENCE = {
    "authorization_policy": [
        "capture_baseline",
        "primary_hypothesis_test",
        "boundary_verification",
        "runtime_config_confirmation",
        "secondary_branch_test",
        "retest_and_closure",
    ],
    "http_routing_misconfiguration": [
        "capture_baseline",
        "boundary_verification",
        "primary_hypothesis_test",
        "runtime_config_confirmation",
        "secondary_branch_test",
        "retest_and_closure",
    ],
    "database_connectivity": [
        "capture_baseline",
        "primary_hypothesis_test",
        "boundary_verification",
        "runtime_config_confirmation",
        "secondary_branch_test",
        "retest_and_closure",
    ],
    "cache_session_store": [
        "capture_baseline",
        "primary_hypothesis_test",
        "runtime_config_confirmation",
        "boundary_verification",
        "secondary_branch_test",
        "retest_and_closure",
    ],
    "model_serving_runtime": [
        "capture_baseline",
        "primary_hypothesis_test",
        "runtime_config_confirmation",
        "boundary_verification",
        "secondary_branch_test",
        "retest_and_closure",
    ],
    "retrieval_embeddings_pipeline": [
        "capture_baseline",
        "primary_hypothesis_test",
        "runtime_config_confirmation",
        "secondary_branch_test",
        "boundary_verification",
        "retest_and_closure",
    ],
    "gpu_inference_runtime": [
        "capture_baseline",
        "primary_hypothesis_test",
        "runtime_config_confirmation",
        "secondary_branch_test",
        "boundary_verification",
        "retest_and_closure",
    ],
}

BASE_STEP_TEMPLATES = [
    {
        "semantic_key": "capture_primary_symptom",
        "step_family": "baseline.capture",
        "phase": "capture_baseline",
        "domains": {"software", "networking", "ai"},
        "families": set(),
        "boundaries": set(),
        "tags": set(),
        "clusters": set(),
        "keywords": {"baseline", "request", "transaction", "symptom", "response"},
        "base_priority": 100,
        "dedupe_group": "baseline_capture",
        "purpose": "capture",
        "title": "Capture one exact failing transaction for the current path",
        "why": "A concise checklist works only when every later verification step is tied to one stable symptom signature.",
        "action": "Reproduce one failing request or workload and record the timestamp, target, inputs, returned status or error, and the first runtime or gateway evidence tied to that exact attempt.",
        "expected_result": "You have one repeatable failing transaction that can be reused to confirm or eliminate each later hypothesis.",
        "if_failed": "If the symptom cannot be reproduced consistently, compare recent deployments, feature flags, and environment differences before deeper diagnosis.",
        "reference_source_type": "official_docs",
        "reference_hint": "request correlation baseline troubleshooting",
    },
    {
        "semantic_key": "boundary_trace",
        "step_family": "boundary.trace",
        "phase": "boundary_verification",
        "domains": {"software", "networking", "ai"},
        "families": set(),
        "boundaries": {"browser_boundary", "proxy_boundary", "network_transport_boundary", "database_boundary", "model_serving_boundary", "gpu_inference_boundary"},
        "tags": set(),
        "clusters": set(),
        "keywords": {"boundary", "hop", "forwarding", "resolution"},
        "base_priority": 82,
        "dedupe_group": "boundary_trace",
        "purpose": "boundary",
        "title": "Trace the request across the {boundary_label}",
        "why": "Boundary-aware troubleshooting works best when the exact handoff between layers is verified instead of assuming propagation is correct.",
        "action": "Inspect the request or workload at both sides of the {boundary_label} and compare headers, payload shape, target selection, protocol details, or execution context before and after that handoff.",
        "expected_result": "The same request intent and metadata survive the {boundary_label} without being rewritten, dropped, or redirected unexpectedly.",
        "if_failed": "If the signal changes across the {boundary_label}, fix that boundary before testing deeper logic.",
        "reference_source_type": "protocol_reference",
        "reference_hint": "boundary propagation verification",
    },
    {
        "semantic_key": "runtime_config_confirmation",
        "step_family": "runtime.config_confirmation",
        "phase": "runtime_config_confirmation",
        "domains": {"software", "networking", "ai"},
        "families": set(),
        "boundaries": {"runtime_boundary", "deployment_change_hint", "database_boundary", "model_serving_boundary", "gpu_inference_boundary"},
        "tags": set(),
        "clusters": set(),
        "keywords": {"runtime", "config", "deploy", "environment", "dependency"},
        "base_priority": 76,
        "dedupe_group": "runtime_config",
        "purpose": "runtime",
        "title": "Confirm live configuration and dependency assumptions on the active runtime",
        "why": "A later verification step is only meaningful if the runtime configuration and dependency set still match the intended stack behavior.",
        "action": "Compare the live configuration, mounted secrets, dependency versions, environment variables, and runtime mode used by the failing path with the intended release settings.",
        "expected_result": "The active runtime configuration and dependency assumptions match the expected stack for the failing path.",
        "if_failed": "If the runtime configuration or dependency set drifted, correct it and rerun the captured failing transaction before continuing.",
        "reference_source_type": "official_docs",
        "reference_hint": "runtime configuration dependency verification",
    },
    {
        "semantic_key": "retest_after_change",
        "step_family": "closure.retest",
        "phase": "retest_and_closure",
        "domains": {"software", "networking", "ai"},
        "families": set(),
        "boundaries": set(),
        "tags": set(),
        "clusters": set(),
        "keywords": {"retest", "closure", "confirm"},
        "base_priority": 100,
        "dedupe_group": "closure_retest",
        "purpose": "closure",
        "title": "Retest the same failing transaction after the first confirmed correction",
        "why": "A troubleshooting workflow is only complete when the original failure is replayed after the first targeted correction instead of assuming the issue is solved.",
        "action": "After the first confirmed correction, replay the exact same captured failing transaction and confirm the original symptom is gone without breaking adjacent paths.",
        "expected_result": "The original failure no longer reproduces and the corrected path behaves consistently under the same test conditions.",
        "if_failed": "If the symptom still reproduces, return to the strongest remaining alternative branch rather than broadening the search randomly.",
        "reference_source_type": "official_docs",
        "reference_hint": "retest after change verification",
    },
]

FAMILY_STEP_TEMPLATES = {
    "authentication": [
        {
            "semantic_key": "auth_artifact_integrity",
            "step_family": "family.authentication.artifact",
            "phase": "primary_hypothesis_test",
            "domains": {"software"},
            "families": {"authentication"},
            "boundaries": {"browser_boundary", "proxy_boundary", "runtime_boundary"},
            "tags": {"authentication", "jwt", "oauth-2.0", "fastapi", "django", "reactjs"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"auth", "token", "cookie", "header"},
            "base_priority": 96,
            "dedupe_group": "auth_artifact",
            "purpose": "hypothesis",
            "title": "Verify the exact identity artifact used by the failing path",
            "why": "Authentication branches become discriminative only when the token, cookie, or session artifact is checked exactly as the service receives it.",
            "action": "Inspect the failing request at the service boundary and confirm the exact token, cookie, session id, host, scheme, and forwarded auth metadata used on the failing path.",
            "expected_result": "The service receives the same identity artifact the caller intended to send, with the expected host and scheme context.",
            "if_failed": "If the identity artifact is missing, altered, or scoped incorrectly, fix that propagation issue before checking claim validation logic.",
            "reference_source_type": "security_guidance",
            "reference_hint": "authentication artifact boundary validation",
        },
        {
            "semantic_key": "auth_claim_validation",
            "step_family": "family.authentication.claims",
            "phase": "secondary_branch_test",
            "domains": {"software"},
            "families": {"authentication", "authorization_policy"},
            "boundaries": {"runtime_boundary"},
            "tags": {"jwt", "oauth-2.0", "authentication", "authorization"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"jwt", "issuer", "audience", "scope", "role"},
            "base_priority": 88,
            "dedupe_group": "auth_claims",
            "purpose": "secondary",
            "title": "Check token claims, issuer, audience, and role or scope mapping",
            "why": "Once artifact integrity is confirmed, the next discriminative branch is whether the token content itself fails authentication or authorization expectations.",
            "action": "Decode one failing identity token and compare issuer, audience, expiry, subject, role, and scope claims with the validation and policy checks used by the failing route.",
            "expected_result": "The token claims satisfy the backend validation and policy requirements for the failing route.",
            "if_failed": "If the token claims do not match the expected auth model, correct issuance or policy mapping before exploring unrelated transport branches.",
            "reference_source_type": "security_guidance",
            "reference_hint": "jwt claims issuer audience scope verification",
        },
    ],
    "authorization_policy": [
        {
            "semantic_key": "authorization_policy_check",
            "step_family": "family.authorization.policy",
            "phase": "primary_hypothesis_test",
            "domains": {"software"},
            "families": {"authorization_policy"},
            "boundaries": {"runtime_boundary", "browser_boundary"},
            "tags": {"authorization", "authentication", "jwt"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"role", "scope", "permission", "policy"},
            "base_priority": 94,
            "dedupe_group": "authorization_policy",
            "purpose": "hypothesis",
            "title": "Evaluate the exact policy decision on the protected operation",
            "why": "Authorization failures should confirm which role, scope, or permission check rejects the live request instead of treating every 403 as a generic access issue.",
            "action": "Trace the failing route through the live authorization checks and compare the authenticated identity, requested action, and required role or scope at the exact denial point.",
            "expected_result": "The precise role, scope, or permission decision on the failing operation is visible and consistent with the intended policy.",
            "if_failed": "If the policy decision does not match the intended permission model, fix the role, scope, or route policy mapping before rechecking transport boundaries.",
            "reference_source_type": "security_guidance",
            "reference_hint": "authorization policy role scope evaluation",
        }
    ],
    "session_identity_boundary": [
        {
            "semantic_key": "session_cookie_boundary",
            "step_family": "family.session.boundary",
            "phase": "boundary_verification",
            "domains": {"software"},
            "families": {"session_identity_boundary"},
            "boundaries": {"browser_boundary", "proxy_boundary"},
            "tags": {"authentication", "authorization", "cors", "reactjs", "django", "fastapi"},
            "clusters": {"auth_identity_flow", "http_proxy_edge"},
            "keywords": {"cookie", "session", "csrf", "credentials"},
            "base_priority": 92,
            "dedupe_group": "session_boundary",
            "purpose": "boundary",
            "title": "Check session, cookie, and credential-mode continuity across the browser boundary",
            "why": "Identity continuity often fails because the browser and backend disagree on cookie scope, CSRF expectations, or credential mode.",
            "action": "Verify SameSite behavior, secure cookie scope, CSRF or trusted-origin settings, and browser credential mode for the exact failing request path.",
            "expected_result": "Session and cookie state remain valid and aligned across the browser-to-backend path.",
            "if_failed": "If browser credential handling breaks identity continuity, fix that state boundary before deeper auth-policy debugging.",
            "reference_source_type": "security_guidance",
            "reference_hint": "session cookie csrf credential mode validation",
        }
    ],
    "cors_proxy_boundary": [
        {
            "semantic_key": "replay_preflight_origin",
            "step_family": "family.cors.preflight",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "networking"},
            "families": {"cors_proxy_boundary"},
            "boundaries": {"browser_boundary", "proxy_boundary"},
            "tags": {"cors", "reactjs", "http", "proxy", "reverse-proxy", "nginx", "apache", "ingress"},
            "clusters": {"http_proxy_edge"},
            "keywords": {"origin", "preflight", "headers"},
            "base_priority": 95,
            "dedupe_group": "cors_preflight",
            "purpose": "hypothesis",
            "title": "Replay the failing preflight or cross-origin request and compare the allowlist response",
            "why": "CORS hypotheses should be confirmed by replaying the real origin, method, and requested headers instead of checking broad config alone.",
            "action": "Replay the failing browser request or OPTIONS preflight with the same Origin, method, and requested headers, then inspect the returned Access-Control response at the backend and edge.",
            "expected_result": "The backend and edge explicitly allow the origin, method, headers, and credentials mode required by the failing browser path.",
            "if_failed": "If the allowlist is incomplete or inconsistent across layers, fix that edge or backend policy before checking unrelated application logic.",
            "reference_source_type": "protocol_reference",
            "reference_hint": "cors preflight allowlist verification",
        }
    ],
    "http_routing_misconfiguration": [
        {
            "semantic_key": "upstream_route_validation",
            "step_family": "family.routing.upstream",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "networking"},
            "families": {"http_routing_misconfiguration"},
            "boundaries": {"proxy_boundary", "network_transport_boundary", "deployment_change_hint"},
            "tags": {"http", "proxy", "reverse-proxy", "nginx", "apache", "routing", "ingress", "load-balancing"},
            "clusters": {"http_proxy_edge", "container_network_surface"},
            "keywords": {"upstream", "route", "gateway", "path"},
            "base_priority": 95,
            "dedupe_group": "routing_upstream",
            "purpose": "hypothesis",
            "title": "Validate the live upstream target, route rewrite, and host preservation behavior",
            "why": "Routing failures are usually confirmed by comparing the live path and upstream target actually used at the edge with the intended backend route.",
            "action": "Inspect the active route, path rewrite, backend service target, upstream host, preserved Host header, and protocol settings for the failing request path.",
            "expected_result": "The live edge configuration targets the intended backend path with the expected host, protocol, and port behavior.",
            "if_failed": "If the route or upstream target is wrong, fix the edge mapping before deeper backend investigation.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "upstream route rewrite host preservation verification",
        }
    ],
    "database_connectivity": [
        {
            "semantic_key": "database_target_runtime_config",
            "step_family": "family.database.target_runtime",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "ai"},
            "families": {"database_connectivity"},
            "boundaries": {"runtime_boundary", "database_boundary", "deployment_change_hint"},
            "tags": {"sql", "postgresql", "mysql", "django", "python", "fastapi"},
            "clusters": {"database_connectivity_stack"},
            "keywords": {"database", "hostname", "secret", "dsn", "environment", "startup"},
            "base_priority": 97,
            "dedupe_group": "database_target_runtime",
            "purpose": "hypothesis",
            "title": "Verify the live database DSN, host, and secret used by the failing runtime",
            "why": "Database startup and connectivity regressions are most discriminative when the live DSN, hostname, and secret source are verified before broader network debugging.",
            "action": "Inspect the live DSN or connection string, database host, port, database name, secret-manager values, injected environment variables, and runtime-specific overrides used by the failing startup or request path.",
            "expected_result": "The failing runtime is using the intended database host, port, database name, and credentials for the affected environment.",
            "if_failed": "If the live DSN, host, or secret is wrong, correct the runtime configuration before testing transport or schema branches.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "database hostname secret dsn runtime target verification",
        },
        {
            "semantic_key": "database_runtime_reachability",
            "step_family": "family.database.connectivity",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "ai"},
            "families": {"database_connectivity"},
            "boundaries": {"database_boundary", "runtime_boundary", "network_transport_boundary"},
            "tags": {"sql", "postgresql", "mysql"},
            "clusters": {"database_connectivity_stack"},
            "keywords": {"database", "connection", "dsn", "pool", "host"},
            "base_priority": 94,
            "dedupe_group": "database_connectivity",
            "purpose": "hypothesis",
            "title": "Test database reachability from the exact runtime context",
            "why": "Database connectivity is only meaningful when tested from the same runtime context and network path used by the failing request.",
            "action": "From the running service context, test DNS resolution, TCP reachability, and one authenticated connection attempt to the configured database host and port used by the failing code path.",
            "expected_result": "The runtime can resolve, reach, and authenticate to the intended database using the configured host, port, and credentials.",
            "if_failed": "If DNS, TCP reachability, or authentication fails from the runtime context, fix that exact boundary before rechecking application logic.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "runtime database reachability verification",
        }
    ],
    "cache_session_store": [
        {
            "semantic_key": "cache_session_consistency",
            "step_family": "family.cache.session",
            "phase": "secondary_branch_test",
            "domains": {"software"},
            "families": {"cache_session_store"},
            "boundaries": {"database_boundary", "runtime_boundary"},
            "tags": {"redis", "authentication", "authorization", "django", "fastapi"},
            "clusters": {"database_connectivity_stack", "auth_identity_flow"},
            "keywords": {"session", "cache", "redis", "state"},
            "base_priority": 87,
            "dedupe_group": "cache_session",
            "purpose": "secondary",
            "title": "Confirm cached identity and session state are current and fully written",
            "why": "Stateful regressions are often secondary branches where the session or cache layer diverges from what the auth or request path expects.",
            "action": "Inspect the cache or session store used by the failing path and confirm the expected identity, session, or state entries are written, current, and visible to the active runtime.",
            "expected_result": "The runtime reads fresh and consistent state from the backing cache or session store during the failing path.",
            "if_failed": "If cached state is stale or incomplete, correct the state-store behavior before tuning unrelated transport or framework settings.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "cache session state consistency verification",
        }
    ],
    "container_networking": [
        {
            "semantic_key": "platform_service_path",
            "step_family": "family.container.path",
            "phase": "boundary_verification",
            "domains": {"software", "networking", "ai"},
            "families": {"container_networking"},
            "boundaries": {"network_transport_boundary", "proxy_boundary", "deployment_change_hint"},
            "tags": {"docker", "kubernetes", "networking", "ingress", "routing", "firewall", "proxy"},
            "clusters": {"container_network_surface"},
            "keywords": {"pod", "service", "policy", "selector", "namespace"},
            "base_priority": 93,
            "dedupe_group": "container_path",
            "purpose": "boundary",
            "title": "Verify service selectors, exposed ports, and network policy on the platform path",
            "why": "Container and platform incidents become diagnosable when selectors, ports, and policy boundaries are checked on the exact service path.",
            "action": "Verify the live service selector, exposed ports, endpoint registration, namespace targeting, and network policy or security-group rules used by the failing service path.",
            "expected_result": "The platform routing layer targets the expected service endpoints and permits the intended traffic path.",
            "if_failed": "If selectors, ports, or policy boundaries are wrong, fix the platform path before deeper application debugging.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "container service selector network policy verification",
        }
    ],
    "dns_service_discovery": [
        {
            "semantic_key": "runtime_dns_resolution",
            "step_family": "family.dns.resolution",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "networking", "ai"},
            "families": {"dns_service_discovery"},
            "boundaries": {"network_transport_boundary", "deployment_change_hint"},
            "tags": {"dns", "networking", "docker", "kubernetes", "routing", "proxy"},
            "clusters": {"tls_dns_transport", "container_network_surface"},
            "keywords": {"dns", "resolver", "hostname", "ttl"},
            "base_priority": 95,
            "dedupe_group": "dns_resolution",
            "purpose": "hypothesis",
            "title": "Resolve the failing hostname from the exact caller context and compare the answer set",
            "why": "DNS and discovery issues should be tested from the actual caller context because search domains and resolver policy often differ across hops.",
            "action": "Resolve the failing hostname from the exact caller context and compare the returned addresses, TTL values, search-domain expansion, and intended service target.",
            "expected_result": "The caller resolves the hostname to the expected current target without stale, empty, or misdirected results.",
            "if_failed": "If the answer set is wrong, fix resolver configuration or service discovery before transport debugging.",
            "reference_source_type": "protocol_reference",
            "reference_hint": "runtime dns answer ttl verification",
        }
    ],
    "tls_edge_termination": [
        {
            "semantic_key": "tls_chain_validation",
            "step_family": "family.tls.chain",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "networking"},
            "families": {"tls_edge_termination"},
            "boundaries": {"proxy_boundary", "network_transport_boundary"},
            "tags": {"ssl", "tls", "nginx", "apache", "proxy", "http"},
            "clusters": {"tls_dns_transport", "http_proxy_edge"},
            "keywords": {"certificate", "handshake", "sni", "trust"},
            "base_priority": 94,
            "dedupe_group": "tls_chain",
            "purpose": "hypothesis",
            "title": "Validate certificate chain, hostname, and TLS termination behavior on the failing edge",
            "why": "TLS issues are best confirmed by checking hostname, certificate chain, and edge termination behavior together from the failing caller path.",
            "action": "Inspect the certificate chain, hostname or SNI, trust path, and TLS termination point used by the failing connection and compare them with the intended edge configuration.",
            "expected_result": "The failing edge presents a valid chain for the expected hostname and the caller trusts that termination path.",
            "if_failed": "If hostname, chain, or termination behavior is wrong, fix the edge certificate path before checking higher-layer routing.",
            "reference_source_type": "security_guidance",
            "reference_hint": "tls certificate chain hostname termination validation",
        }
    ],
    "model_serving_runtime": [
        {
            "semantic_key": "model_runtime_validation",
            "step_family": "family.ai.serving_runtime",
            "phase": "primary_hypothesis_test",
            "domains": {"ai"},
            "families": {"model_serving_runtime"},
            "boundaries": {"model_serving_boundary", "runtime_boundary", "deployment_change_hint"},
            "tags": {"model-serving", "large-language-model", "inference", "huggingface-transformers", "sentence-transformers"},
            "clusters": {"model_serving_pipeline"},
            "keywords": {"model", "tokenizer", "serving", "endpoint"},
            "base_priority": 95,
            "dedupe_group": "model_runtime",
            "purpose": "hypothesis",
            "title": "Validate model artifacts, runtime mode, and serving startup assumptions",
            "why": "Model-serving failures are most discriminative when artifact loading, runtime mode, and serving startup behavior are checked together on the live path.",
            "action": "Confirm the runtime loads the intended model artifacts, tokenizer assets, serving configuration, and startup mode for the exact failing serving endpoint.",
            "expected_result": "The serving runtime loads the intended artifacts and configuration for the failing path without fallback or startup drift.",
            "if_failed": "If the serving runtime is loading the wrong artifacts or mode, fix that serving path before tuning request shape or capacity.",
            "reference_source_type": "library_docs",
            "reference_hint": "model serving runtime artifact validation",
        }
    ],
    "retrieval_embeddings_pipeline": [
        {
            "semantic_key": "retrieval_vector_alignment",
            "step_family": "family.ai.retrieval",
            "phase": "secondary_branch_test",
            "domains": {"ai"},
            "families": {"retrieval_embeddings_pipeline"},
            "boundaries": {"model_serving_boundary", "database_boundary", "runtime_boundary"},
            "tags": {"rag", "embeddings", "vector-database", "sentence-transformers", "model-serving"},
            "clusters": {"model_serving_pipeline", "database_connectivity_stack"},
            "keywords": {"embedding", "vector", "index", "retrieval"},
            "base_priority": 91,
            "dedupe_group": "retrieval_vector",
            "purpose": "secondary",
            "title": "Check embedding generation and vector-store assumptions on the retrieval branch",
            "why": "Retrieval regressions are often secondary branches where vector generation, indexing, or lookup assumptions drift away from the live request path.",
            "action": "Verify the embedding model, vector-store target, index contract, and retrieval parameters used on the failing request branch.",
            "expected_result": "The retrieval branch uses the intended embedding model, vector-store target, and query contract for the failing path.",
            "if_failed": "If embeddings or vector lookup assumptions diverge, fix that retrieval branch before changing the core serving runtime.",
            "reference_source_type": "library_docs",
            "reference_hint": "embedding vector store retrieval verification",
        }
    ],
    "gpu_inference_runtime": [
        {
            "semantic_key": "tensor_shape_capture",
            "step_family": "family.ai.tensor_shape",
            "phase": "primary_hypothesis_test",
            "domains": {"ai"},
            "families": {"gpu_inference_runtime"},
            "boundaries": {"gpu_inference_boundary", "model_serving_boundary", "runtime_boundary"},
            "tags": {"pytorch", "numpy", "inference", "machine-learning"},
            "clusters": {"gpu_acceleration_stack", "model_serving_pipeline"},
            "keywords": {"shape", "tensor", "dimension", "feature", "linear", "layer", "mat1", "mat2"},
            "base_priority": 97,
            "dedupe_group": "tensor_shape",
            "purpose": "hypothesis",
            "title": "Log and compare tensor shapes at model.forward input against the first layer contract",
            "why": "Tensor shape mismatches are most actionable when the exact input shape is captured and compared with the model's expected dimensions before any GPU or runtime investigation.",
            "action": "Add shape logging before model.forward() and compare the input tensor dimensions with the first layer's expected in_features, weight shape, or model input contract.",
            "expected_result": "The input tensor shape matches the model's first layer or input contract exactly, with correct feature count, batch dimension, and sequence length.",
            "if_failed": "If the shape does not match, trace the preprocessing or data loading path to find where the dimension diverges from the model contract.",
            "reference_source_type": "library_docs",
            "reference_hint": "pytorch tensor shape model forward input dimensions",
        },
        {
            "semantic_key": "tensor_conversion_validation",
            "step_family": "family.ai.tensor_conversion",
            "phase": "boundary_verification",
            "domains": {"ai"},
            "families": {"gpu_inference_runtime"},
            "boundaries": {"gpu_inference_boundary", "runtime_boundary"},
            "tags": {"pytorch", "numpy", "inference"},
            "clusters": {"gpu_acceleration_stack"},
            "keywords": {"numpy", "conversion", "dtype", "layout", "transpose", "contiguous", "batch", "padding"},
            "base_priority": 94,
            "dedupe_group": "tensor_conversion",
            "purpose": "boundary",
            "title": "Validate NumPy-to-PyTorch conversion, dtype, and dimension ordering",
            "why": "NumPy-to-PyTorch conversion often changes dtype, layout, or dimension order silently, introducing shape mismatches that only surface at the first linear layer.",
            "action": "Inspect the conversion from NumPy arrays to PyTorch tensors and verify dtype, dimension ordering (e.g. channels-first vs channels-last), contiguity, and any padding or transpose operations.",
            "expected_result": "The conversion preserves the intended dtype, dimension order, and layout expected by the model's input contract.",
            "if_failed": "If the conversion changes layout or dtype unexpectedly, fix the preprocessing pipeline before checking model weights or GPU configuration.",
            "reference_source_type": "library_docs",
            "reference_hint": "pytorch numpy conversion dtype layout dimension order",
        },
        {
            "semantic_key": "gpu_runtime_pressure",
            "step_family": "family.ai.gpu_runtime",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": {"gpu_inference_runtime"},
            "boundaries": {"gpu_inference_boundary", "runtime_boundary", "deployment_change_hint"},
            "tags": {"gpu", "cuda", "inference", "pytorch", "tensorflow"},
            "clusters": {"gpu_acceleration_stack", "model_serving_pipeline"},
            "keywords": {"gpu", "cuda", "memory", "vram", "precision"},
            "base_priority": 94,
            "dedupe_group": "gpu_runtime",
            "purpose": "runtime",
            "title": "Measure accelerator headroom, device placement, and runtime compatibility",
            "why": "GPU-backed failures are most actionable when memory pressure, device placement, and runtime compatibility are measured together on the failing workload.",
            "action": "Inspect GPU memory usage, device placement, runtime compatibility, concurrency pressure, and any fallback to CPU during the failing workload.",
            "expected_result": "The intended accelerator remains active with compatible runtime settings and enough headroom for the failing workload.",
            "if_failed": "If the accelerator is saturated or incompatible, correct that runtime issue before changing higher-level serving or network logic.",
            "reference_source_type": "library_docs",
            "reference_hint": "gpu device placement memory runtime compatibility",
        },
    ],
}

BOUNDARY_STEP_TEMPLATES = {
    "browser_boundary": [
        {
            "semantic_key": "browser_request_shape",
            "step_family": "boundary.browser.request_shape",
            "phase": "boundary_verification",
            "domains": {"software", "networking"},
            "families": set(),
            "boundaries": {"browser_boundary"},
            "tags": {"cors", "reactjs", "javascript", "typescript", "authentication", "authorization"},
            "clusters": {"auth_identity_flow", "http_proxy_edge"},
            "keywords": {"browser", "origin", "cookie", "credentials"},
            "base_priority": 90,
            "dedupe_group": "browser_shape",
            "purpose": "boundary",
            "title": "Inspect the exact browser request shape on the failing path",
            "why": "Browser-side incidents should confirm the live Origin, credentials mode, cookie behavior, and request headers rather than assuming the frontend sent the intended shape.",
            "action": "Use the browser network trace to inspect the exact request and any preflight, including Origin, credentials mode, cookies, Authorization header, and requested methods or headers.",
            "expected_result": "The browser sends the request shape the backend and edge are expected to receive on the failing path.",
            "if_failed": "If the browser request shape is wrong, fix the client or origin policy before deeper backend investigation.",
            "reference_source_type": "official_docs",
            "reference_hint": "browser request shape origin credentials inspection",
        }
    ],
    "proxy_boundary": [
        {
            "semantic_key": "proxy_forwarding_alignment",
            "step_family": "boundary.proxy.forwarding",
            "phase": "boundary_verification",
            "domains": {"software", "networking", "ai"},
            "families": set(),
            "boundaries": {"proxy_boundary"},
            "tags": {"proxy", "reverse-proxy", "nginx", "apache", "ingress", "http"},
            "clusters": {"http_proxy_edge", "container_network_surface"},
            "keywords": {"proxy", "host", "forwarded", "upstream"},
            "base_priority": 91,
            "dedupe_group": "proxy_forwarding",
            "purpose": "boundary",
            "title": "Check forwarding headers, host preservation, and upstream selection at the proxy boundary",
            "why": "Proxy-boundary failures usually come from rewritten host, auth, origin, or upstream targeting rather than from business logic alone.",
            "action": "Inspect the proxy or ingress behavior for forwarded headers, preserved host, chosen upstream target, protocol expectations, and any rewrite or redirect rules on the failing path.",
            "expected_result": "The proxy forwards the intended host, headers, and upstream target for the failing request path.",
            "if_failed": "If the proxy boundary rewrites or forwards the wrong values, fix that edge behavior before deeper runtime diagnosis.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "proxy forwarding host upstream alignment",
        }
    ],
    "database_boundary": [
        {
            "semantic_key": "database_contract_boundary",
            "step_family": "boundary.database.contract",
            "phase": "runtime_config_confirmation",
            "domains": {"software", "ai"},
            "families": set(),
            "boundaries": {"database_boundary"},
            "tags": {"sql", "postgresql", "mysql"},
            "clusters": {"database_connectivity_stack"},
            "keywords": {"database", "schema", "state", "connection"},
            "base_priority": 84,
            "dedupe_group": "database_boundary",
            "purpose": "runtime",
            "title": "Confirm the runtime is using the intended database target and schema contract",
            "why": "Data-path failures often persist because the runtime points to the wrong database target or expects a different schema contract than the live target provides.",
            "action": "Confirm the runtime target, schema contract, and connection settings used by the failing database path.",
            "expected_result": "The runtime targets the intended database with the expected schema contract and connection settings.",
            "if_failed": "If the database target or schema contract differs, correct it before retesting the failing transaction.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "database contract target verification",
        }
    ],
    "network_transport_boundary": [
        {
            "semantic_key": "transport_hop_validation",
            "step_family": "boundary.transport.hops",
            "phase": "secondary_branch_test",
            "domains": {"software", "networking", "ai"},
            "families": set(),
            "boundaries": {"network_transport_boundary"},
            "tags": {"networking", "dns", "ssl", "tls", "tcp", "routing", "firewall", "vpn"},
            "clusters": {"tls_dns_transport", "container_network_surface"},
            "keywords": {"network", "route", "resolver", "certificate", "port"},
            "base_priority": 86,
            "dedupe_group": "transport_hops",
            "purpose": "secondary",
            "title": "Validate hop-by-hop transport behavior on the failing path",
            "why": "Transport failures should confirm which hop, resolver, or TLS or TCP transition actually breaks instead of treating the network path as one opaque layer.",
            "action": "Verify hop-by-hop resolution, reachability, port exposure, TLS or TCP behavior, and the first transport boundary where the request diverges from the expected path.",
            "expected_result": "Each transport hop behaves as expected or the first failing boundary is isolated clearly.",
            "if_failed": "If a transport hop fails, fix that boundary before continuing with higher-level runtime checks.",
            "reference_source_type": "protocol_reference",
            "reference_hint": "transport hop by hop verification",
        }
    ],
    "model_serving_boundary": [
        {
            "semantic_key": "model_serving_branch",
            "step_family": "boundary.model_serving.branch",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": set(),
            "boundaries": {"model_serving_boundary"},
            "tags": {"model-serving", "large-language-model", "inference", "embeddings", "rag", "huggingface-transformers", "sentence-transformers"},
            "clusters": {"model_serving_pipeline"},
            "keywords": {"model", "serving", "endpoint", "embedding"},
            "base_priority": 88,
            "dedupe_group": "model_serving_boundary",
            "purpose": "runtime",
            "title": "Confirm the serving branch, model endpoint, and runtime mode used by the failing workload",
            "why": "Serving incidents persist when the failing request reaches a different model branch, endpoint, or runtime mode than the one engineers intend to inspect.",
            "action": "Verify the exact serving endpoint, model branch, runtime mode, and workload path used by the failing AI request or retrieval flow.",
            "expected_result": "The failing workload is handled by the intended serving branch with the expected runtime mode.",
            "if_failed": "If the serving branch or endpoint is wrong, correct that path before tuning models or transport settings.",
            "reference_source_type": "library_docs",
            "reference_hint": "model serving endpoint branch verification",
        }
    ],
    "gpu_inference_boundary": [
        {
            "semantic_key": "gpu_workload_shape",
            "step_family": "boundary.gpu.workload",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": set(),
            "boundaries": {"gpu_inference_boundary"},
            "tags": {"gpu", "cuda", "inference", "pytorch", "tensorflow"},
            "clusters": {"gpu_acceleration_stack"},
            "keywords": {"gpu", "cuda", "batch", "memory", "sequence"},
            "base_priority": 89,
            "dedupe_group": "gpu_workload",
            "purpose": "runtime",
            "title": "Compare workload shape with GPU memory and execution headroom",
            "why": "GPU incidents are rarely generic; they usually come from workload shape, memory pressure, or device-placement mismatches on the failing path.",
            "action": "Measure batch size, sequence length, memory usage, device placement, and concurrency on the failing workload and compare them with a smaller stable baseline.",
            "expected_result": "The workload fits within the active GPU memory and execution budget without unexpected fallback behavior.",
            "if_failed": "If workload shape exceeds headroom, reduce pressure or fix placement before changing retrieval or serving logic.",
            "reference_source_type": "library_docs",
            "reference_hint": "gpu workload shape memory headroom verification",
        }
    ],
    "deployment_change_hint": [
        {
            "semantic_key": "deployment_regression_check",
            "step_family": "boundary.deployment.regression",
            "phase": "runtime_config_confirmation",
            "domains": {"software", "networking", "ai"},
            "families": set(),
            "boundaries": {"deployment_change_hint"},
            "tags": {"docker", "kubernetes", "ingress", "mlops", "debugging"},
            "clusters": {"container_network_surface", "model_serving_pipeline"},
            "keywords": {"deploy", "upgrade", "rollback", "restart"},
            "base_priority": 85,
            "dedupe_group": "deployment_regression",
            "purpose": "runtime",
            "title": "Compare live behavior against the last known-good deployment state",
            "why": "Deployment-aware troubleshooting should confirm which runtime, route, artifact, or dependency changed before broadening the search.",
            "action": "Compare the failing path with the last known-good deployment state, focusing on changed routes, dependencies, config, artifacts, and service targets introduced by the recent change.",
            "expected_result": "The specific deployment change that affects the failing path is either ruled out or isolated clearly.",
            "if_failed": "If the regression is tied to a recent deployment change, fix or roll back that specific change before deeper hypothesis testing.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "deployment regression change comparison",
        }
    ],
}

TAG_STEP_TEMPLATES = {
    "fastapi": [
        {
            "semantic_key": "fastapi_dependency_path",
            "step_family": "tag.fastapi.dependency_path",
            "phase": "runtime_config_confirmation",
            "domains": {"software"},
            "families": {"authentication", "authorization_policy", "database_connectivity"},
            "boundaries": {"runtime_boundary"},
            "tags": {"fastapi"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"dependency", "middleware", "startup"},
            "base_priority": 84,
            "dedupe_group": "framework_runtime",
            "purpose": "runtime",
            "title": "Trace FastAPI dependency, middleware, and startup behavior on the failing route",
            "why": "FastAPI regressions often come from dependency injection, middleware ordering, or startup state instead of the route handler alone.",
            "action": "Trace the failing FastAPI route through its dependencies, middleware, and startup state and confirm required auth or data dependencies are initialized on the live request path.",
            "expected_result": "The failing route receives the expected dependency state and middleware order for the active runtime.",
            "if_failed": "If dependency or middleware state is wrong, fix that runtime path before exploring unrelated transport branches.",
            "reference_source_type": "library_docs",
            "reference_hint": "fastapi dependency middleware startup trace",
        }
    ],
    "django": [
        {
            "semantic_key": "django_security_runtime",
            "step_family": "tag.django.security_runtime",
            "phase": "runtime_config_confirmation",
            "domains": {"software"},
            "families": {"authentication", "session_identity_boundary", "cors_proxy_boundary"},
            "boundaries": {"runtime_boundary", "browser_boundary"},
            "tags": {"django"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"csrf", "host", "cookie", "trusted"},
            "base_priority": 82,
            "dedupe_group": "framework_runtime",
            "purpose": "runtime",
            "title": "Verify Django security, cookie, and trusted-origin settings on the failing path",
            "why": "Django production failures often come from cookie, host, or trusted-origin settings that drift from the deployed edge reality.",
            "action": "Review the live Django security and host settings used by the failing request, including trusted origins, cookie scope, secure proxy handling, and host validation.",
            "expected_result": "Django security settings align with the deployed hostnames, scheme, and browser flow for the failing path.",
            "if_failed": "If live Django security settings do not match deployment reality, fix them before deeper auth or routing investigation.",
            "reference_source_type": "security_guidance",
            "reference_hint": "django security trusted origin cookie verification",
        }
    ],
    "jwt": [
        {
            "semantic_key": "jwt_claim_integrity",
            "step_family": "tag.jwt.claim_integrity",
            "phase": "primary_hypothesis_test",
            "domains": {"software"},
            "families": {"authentication", "authorization_policy"},
            "boundaries": {"runtime_boundary"},
            "tags": {"jwt"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"jwt", "claims", "signature", "audience"},
            "base_priority": 92,
            "dedupe_group": "auth_claims",
            "purpose": "hypothesis",
            "title": "Decode one failing JWT and inspect claim integrity against the live validator",
            "why": "JWT cases become precise when the failing token is compared directly with the live validation expectations instead of assuming a generic auth issue.",
            "action": "Decode one failing JWT and compare issuer, audience, expiry, signing algorithm, scope, and role claims with the validator settings used on the failing route.",
            "expected_result": "The live validator accepts the token claims exactly as issued for the failing route.",
            "if_failed": "If claim integrity or validator settings do not align, fix that token path before checking unrelated boundaries.",
            "reference_source_type": "security_guidance",
            "reference_hint": "jwt claim integrity live validator comparison",
        }
    ],
    "cors": [
        {
            "semantic_key": "cors_origin_alignment",
            "step_family": "tag.cors.origin_alignment",
            "phase": "boundary_verification",
            "domains": {"software", "networking"},
            "families": {"cors_proxy_boundary", "session_identity_boundary"},
            "boundaries": {"browser_boundary", "proxy_boundary"},
            "tags": {"cors"},
            "clusters": {"http_proxy_edge"},
            "keywords": {"origin", "preflight", "allow"},
            "base_priority": 90,
            "dedupe_group": "cors_preflight",
            "purpose": "boundary",
            "title": "Compare the failing origin path with the live CORS allowlist across edge and backend",
            "why": "CORS cases are only resolved when the live origin path and the actual allowlist are compared across every layer that touches the request.",
            "action": "Compare the failing browser origin, requested method, headers, and credential mode with the live allowlist and preflight behavior implemented at the backend and any edge layer.",
            "expected_result": "The live allowlist matches the failing origin path end to end.",
            "if_failed": "If the origin path is not allowed consistently across layers, fix that policy before deeper auth or routing investigation.",
            "reference_source_type": "protocol_reference",
            "reference_hint": "cors origin allowlist end to end comparison",
        }
    ],
    "reactjs": [
        {
            "semantic_key": "react_request_construction",
            "step_family": "tag.react.request_construction",
            "phase": "boundary_verification",
            "domains": {"software"},
            "families": {"authentication", "cors_proxy_boundary", "session_identity_boundary"},
            "boundaries": {"browser_boundary"},
            "tags": {"reactjs", "javascript", "typescript"},
            "clusters": {"http_proxy_edge", "auth_identity_flow"},
            "keywords": {"frontend", "fetch", "credentials", "header"},
            "base_priority": 83,
            "dedupe_group": "browser_shape",
            "purpose": "boundary",
            "title": "Inspect the exact React request construction used by the failing interaction",
            "why": "React-side incidents often come from the live request shape differing from what the backend expects rather than from backend logic alone.",
            "action": "Inspect the network trace for the React interaction and confirm request method, fetch or axios options, credentials mode, headers, cookies, and any preflight behavior used by the failing call.",
            "expected_result": "The React client constructs the request exactly as the backend and edge path expect.",
            "if_failed": "If the request construction differs, fix the client request shape before deeper backend debugging.",
            "reference_source_type": "official_docs",
            "reference_hint": "react request construction network trace verification",
        }
    ],
    "nginx": [
        {
            "semantic_key": "nginx_edge_directives",
            "step_family": "tag.nginx.edge_directives",
            "phase": "boundary_verification",
            "domains": {"software", "networking"},
            "families": {"http_routing_misconfiguration", "cors_proxy_boundary", "tls_edge_termination"},
            "boundaries": {"proxy_boundary"},
            "tags": {"nginx", "proxy", "reverse-proxy"},
            "clusters": {"http_proxy_edge"},
            "keywords": {"upstream", "header", "timeout", "host"},
            "base_priority": 88,
            "dedupe_group": "proxy_forwarding",
            "purpose": "boundary",
            "title": "Review the live nginx directives that shape the failing path",
            "why": "Nginx often changes headers, host preservation, timeout budgets, or upstream selection in ways that dominate the failure mode.",
            "action": "Review the live nginx directives affecting the failing path, including upstream target, forwarded headers, host handling, timeout settings, and any path rewrite behavior.",
            "expected_result": "The nginx layer preserves the intended request semantics and targets the correct backend path.",
            "if_failed": "If nginx behavior changes the path unexpectedly, fix that edge configuration before application-level debugging.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "nginx live directives failing path review",
        }
    ],
    "proxy": [
        {
            "semantic_key": "proxy_header_boundary",
            "step_family": "tag.proxy.header_boundary",
            "phase": "boundary_verification",
            "domains": {"software", "networking", "ai"},
            "families": {"http_routing_misconfiguration", "authentication", "cors_proxy_boundary", "tls_edge_termination"},
            "boundaries": {"proxy_boundary"},
            "tags": {"proxy", "reverse-proxy", "http"},
            "clusters": {"http_proxy_edge", "tls_dns_transport"},
            "keywords": {"header", "host", "scheme", "upstream"},
            "base_priority": 87,
            "dedupe_group": "proxy_forwarding",
            "purpose": "boundary",
            "title": "Verify proxy header forwarding, scheme preservation, and upstream targeting on the failing branch",
            "why": "Proxy-driven incidents typically come from header rewriting or upstream targeting mismatches that change the semantics of the failing request.",
            "action": "Verify forwarded host, scheme, client, auth, and origin headers and compare the chosen upstream target with the intended failing branch.",
            "expected_result": "The proxy preserves the intended request semantics and routes the request to the correct upstream branch.",
            "if_failed": "If header forwarding or upstream targeting is wrong, fix the proxy branch before deeper runtime analysis.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "proxy header scheme upstream target verification",
        }
    ],
    "dns": [
        {
            "semantic_key": "dns_answer_validation",
            "step_family": "tag.dns.answer_validation",
            "phase": "primary_hypothesis_test",
            "domains": {"software", "networking", "ai"},
            "families": {"dns_service_discovery"},
            "boundaries": {"network_transport_boundary", "deployment_change_hint"},
            "tags": {"dns"},
            "clusters": {"tls_dns_transport", "container_network_surface"},
            "keywords": {"dns", "answer", "ttl", "resolver"},
            "base_priority": 92,
            "dedupe_group": "dns_resolution",
            "purpose": "hypothesis",
            "title": "Compare live DNS answers, TTL behavior, and resolver selection for the failing target",
            "why": "DNS failures often hide behind stale answers, wrong search domains, or an unexpected resolver path that only appears in the failing runtime context.",
            "action": "Inspect the live DNS answers, TTL values, search-domain behavior, and resolver path used for the failing target from the same caller context that experiences the problem.",
            "expected_result": "The caller receives the expected current answer set from the intended resolver path for the failing target.",
            "if_failed": "If DNS answers or resolver behavior differ, correct the discovery path before deeper transport or application checks.",
            "reference_source_type": "protocol_reference",
            "reference_hint": "dns answers ttl resolver path verification",
        }
    ],
    "postgresql": [
        {
            "semantic_key": "postgresql_schema_state",
            "step_family": "tag.postgresql.schema_state",
            "phase": "runtime_config_confirmation",
            "domains": {"software", "ai"},
            "families": {"database_connectivity"},
            "boundaries": {"database_boundary"},
            "tags": {"postgresql", "sql"},
            "clusters": {"database_connectivity_stack"},
            "keywords": {"schema", "migration", "search path"},
            "base_priority": 83,
            "dedupe_group": "database_boundary",
            "purpose": "runtime",
            "title": "Confirm PostgreSQL target, schema state, and migration alignment for the failing path",
            "why": "PostgreSQL incidents often persist because the runtime points to a valid database that still has the wrong schema or migration state for the live code path.",
            "action": "Verify the active PostgreSQL target, schema search path, applied migrations, and required tables or columns for the exact failing code path.",
            "expected_result": "The runtime points to the intended PostgreSQL target and the live schema matches the failing code path.",
            "if_failed": "If the PostgreSQL target or schema state is wrong, correct it before further application-layer diagnosis.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "postgresql target schema migration alignment",
        }
    ],
    "mysql": [
        {
            "semantic_key": "mysql_target_contract",
            "step_family": "tag.mysql.target_contract",
            "phase": "runtime_config_confirmation",
            "domains": {"software", "ai"},
            "families": {"database_connectivity"},
            "boundaries": {"database_boundary"},
            "tags": {"mysql", "sql"},
            "clusters": {"database_connectivity_stack"},
            "keywords": {"schema", "connection", "permissions"},
            "base_priority": 82,
            "dedupe_group": "database_boundary",
            "purpose": "runtime",
            "title": "Confirm MySQL target, privileges, and schema expectations for the failing path",
            "why": "MySQL failures often come from the runtime connecting successfully to a target that still has the wrong privileges or schema assumptions for the live code path.",
            "action": "Verify the active MySQL target, credentials, required privileges, and live schema assumptions used by the failing request path.",
            "expected_result": "The runtime points to the intended MySQL target with the privileges and schema expected by the failing path.",
            "if_failed": "If target, privileges, or schema expectations differ, correct them before deeper application debugging.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "mysql target privileges schema verification",
        }
    ],
    "redis": [
        {
            "semantic_key": "redis_state_path",
            "step_family": "tag.redis.state_path",
            "phase": "secondary_branch_test",
            "domains": {"software", "ai"},
            "families": {"cache_session_store", "database_connectivity"},
            "boundaries": {"database_boundary", "runtime_boundary"},
            "tags": {"redis"},
            "clusters": {"database_connectivity_stack"},
            "keywords": {"cache", "session", "state", "ttl"},
            "base_priority": 81,
            "dedupe_group": "cache_session",
            "purpose": "secondary",
            "title": "Verify Redis state, TTL behavior, and cache consistency on the failing branch",
            "why": "Redis-backed state issues often appear as secondary failures where cache contents or TTL behavior diverge from what the runtime expects.",
            "action": "Inspect the Redis keys, TTL values, and state consistency relevant to the failing path and compare them with the runtime expectations for that branch.",
            "expected_result": "Redis state for the failing branch is current, complete, and aligned with runtime expectations.",
            "if_failed": "If Redis state is stale or inconsistent, correct that cache path before further route or policy debugging.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "redis state ttl cache consistency verification",
        }
    ],
    "docker": [
        {
            "semantic_key": "docker_runtime_context",
            "step_family": "tag.docker.runtime_context",
            "phase": "runtime_config_confirmation",
            "domains": {"software", "networking", "ai"},
            "families": {"container_networking", "model_serving_runtime"},
            "boundaries": {"deployment_change_hint", "runtime_boundary"},
            "tags": {"docker"},
            "clusters": {"container_network_surface"},
            "keywords": {"image", "container", "env", "mount"},
            "base_priority": 80,
            "dedupe_group": "deployment_regression",
            "purpose": "runtime",
            "title": "Confirm the container image, mounts, and runtime env used by the failing path",
            "why": "Container regressions often come from image drift, missing mounts, or runtime environment differences rather than from the workload logic alone.",
            "action": "Confirm the running container image, mounts, env vars, exposed ports, and runtime arguments used by the failing path.",
            "expected_result": "The failing path is running inside the intended container image and runtime context.",
            "if_failed": "If container image or runtime context drifted, correct that deployment state before deeper service debugging.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "container image mounts runtime env verification",
        }
    ],
    "kubernetes": [
        {
            "semantic_key": "kubernetes_service_mapping",
            "step_family": "tag.kubernetes.service_mapping",
            "phase": "boundary_verification",
            "domains": {"software", "networking", "ai"},
            "families": {"container_networking", "http_routing_misconfiguration"},
            "boundaries": {"deployment_change_hint", "proxy_boundary", "network_transport_boundary"},
            "tags": {"kubernetes", "ingress", "routing"},
            "clusters": {"container_network_surface"},
            "keywords": {"service", "selector", "endpoint", "namespace"},
            "base_priority": 89,
            "dedupe_group": "container_path",
            "purpose": "boundary",
            "title": "Check Kubernetes service, endpoint, and ingress mapping on the failing path",
            "why": "Kubernetes incidents often come from service selectors, endpoint registration, or ingress wiring that no longer match the intended traffic path.",
            "action": "Check the live Kubernetes service selector, endpoints, ingress mapping, namespace targeting, and exposed service ports used by the failing path.",
            "expected_result": "The failing path targets the intended Kubernetes service endpoints and ingress route.",
            "if_failed": "If service or ingress mapping is wrong, fix the platform path before deeper application or model debugging.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "kubernetes service endpoint ingress mapping verification",
        }
    ],
    "model-serving": [
        {
            "semantic_key": "serving_endpoint_mode",
            "step_family": "tag.model_serving.endpoint_mode",
            "phase": "primary_hypothesis_test",
            "domains": {"ai"},
            "families": {"model_serving_runtime"},
            "boundaries": {"model_serving_boundary", "deployment_change_hint"},
            "tags": {"model-serving", "large-language-model", "inference"},
            "clusters": {"model_serving_pipeline"},
            "keywords": {"endpoint", "runtime", "serving"},
            "base_priority": 90,
            "dedupe_group": "model_runtime",
            "purpose": "hypothesis",
            "title": "Confirm the failing request is handled by the intended serving endpoint and runtime mode",
            "why": "Serving incidents often persist because the failing request hits a different endpoint or execution mode than the one engineers expect.",
            "action": "Verify the exact serving endpoint, model branch, execution mode, and deployment target that handled the failing AI request.",
            "expected_result": "The failing AI request is handled by the intended serving endpoint and runtime mode.",
            "if_failed": "If the serving endpoint or runtime mode is wrong, correct that branch before tuning artifacts or accelerators.",
            "reference_source_type": "library_docs",
            "reference_hint": "serving endpoint runtime mode verification",
        }
    ],
    "rag": [
        {
            "semantic_key": "rag_retrieval_path",
            "step_family": "tag.rag.retrieval_path",
            "phase": "secondary_branch_test",
            "domains": {"ai"},
            "families": {"retrieval_embeddings_pipeline"},
            "boundaries": {"model_serving_boundary", "database_boundary"},
            "tags": {"rag", "embeddings", "vector-database"},
            "clusters": {"model_serving_pipeline", "database_connectivity_stack"},
            "keywords": {"retrieval", "context", "vector", "index"},
            "base_priority": 87,
            "dedupe_group": "retrieval_vector",
            "purpose": "secondary",
            "title": "Verify retrieval context, vector lookup, and document selection on the failing branch",
            "why": "RAG failures often come from retrieval context or vector lookup diverging from the model-serving assumptions rather than from generation alone.",
            "action": "Verify the documents, vector lookup target, retrieval parameters, and context assembly used by the failing RAG path.",
            "expected_result": "The failing path retrieves the intended context from the correct vector target with the expected parameters.",
            "if_failed": "If retrieval context or vector lookup is wrong, fix that branch before tuning the serving runtime itself.",
            "reference_source_type": "library_docs",
            "reference_hint": "rag retrieval context vector lookup verification",
        }
    ],
    "embeddings": [
        {
            "semantic_key": "embedding_shape_profile",
            "step_family": "tag.embeddings.shape_profile",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": {"retrieval_embeddings_pipeline", "gpu_inference_runtime"},
            "boundaries": {"model_serving_boundary", "gpu_inference_boundary"},
            "tags": {"embeddings", "sentence-transformers", "inference"},
            "clusters": {"model_serving_pipeline", "gpu_acceleration_stack"},
            "keywords": {"embedding", "batch", "sequence", "latency"},
            "base_priority": 85,
            "dedupe_group": "gpu_workload",
            "purpose": "runtime",
            "title": "Measure embedding batch shape and latency behavior on the failing workload",
            "why": "Embedding paths often regress when batch shape, sequence length, or concurrency drift from the serving assumptions used by the runtime.",
            "action": "Measure embedding batch size, longest sequence length, concurrency, and latency behavior for the failing workload and compare them with a smaller healthy baseline.",
            "expected_result": "The embedding workload stays within the runtime's expected latency and memory envelope.",
            "if_failed": "If batch shape or latency drift is significant, reduce pressure or correct workload shaping before deeper model debugging.",
            "reference_source_type": "library_docs",
            "reference_hint": "embedding batch shape latency verification",
        }
    ],
    "pytorch": [
        {
            "semantic_key": "pytorch_runtime_alignment",
            "step_family": "tag.pytorch.runtime_alignment",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": {"model_serving_runtime", "gpu_inference_runtime"},
            "boundaries": {"runtime_boundary", "gpu_inference_boundary"},
            "tags": {"pytorch", "cuda", "gpu"},
            "clusters": {"gpu_acceleration_stack", "model_serving_pipeline"},
            "keywords": {"pytorch", "device", "runtime", "precision"},
            "base_priority": 84,
            "dedupe_group": "gpu_runtime",
            "purpose": "runtime",
            "title": "Check PyTorch runtime build, device placement, and precision assumptions",
            "why": "PyTorch-serving incidents are usually resolved by confirming the live runtime build, device placement, and precision mode used by the failing workload.",
            "action": "Check the live PyTorch build, device placement, precision mode, and any runtime compatibility warnings or fallback behavior on the failing workload.",
            "expected_result": "PyTorch runtime settings align with the intended accelerator and serving assumptions for the failing workload.",
            "if_failed": "If runtime alignment is wrong, fix that stack issue before deeper model or retrieval debugging.",
            "reference_source_type": "library_docs",
            "reference_hint": "pytorch runtime build device precision verification",
        }
    ],
    "cuda": [
        {
            "semantic_key": "cuda_capacity_check",
            "step_family": "tag.cuda.capacity_check",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": {"gpu_inference_runtime"},
            "boundaries": {"gpu_inference_boundary"},
            "tags": {"cuda", "gpu", "inference"},
            "clusters": {"gpu_acceleration_stack"},
            "keywords": {"cuda", "memory", "driver", "runtime"},
            "base_priority": 86,
            "dedupe_group": "gpu_runtime",
            "purpose": "runtime",
            "title": "Confirm CUDA runtime compatibility and memory headroom on the failing workload",
            "why": "CUDA failures usually come from runtime compatibility or memory pressure rather than from model semantics, so they should be validated directly.",
            "action": "Confirm driver and CUDA runtime compatibility, inspect memory headroom, and compare the failing workload with a smaller stable baseline on the same device.",
            "expected_result": "CUDA runtime compatibility and memory headroom are sufficient for the failing workload.",
            "if_failed": "If CUDA compatibility or headroom is insufficient, correct that runtime issue before continuing.",
            "reference_source_type": "library_docs",
            "reference_hint": "cuda runtime compatibility memory headroom verification",
        }
    ],
    "gpu": [
        {
            "semantic_key": "gpu_utilization_check",
            "step_family": "tag.gpu.utilization_check",
            "phase": "runtime_config_confirmation",
            "domains": {"ai"},
            "families": {"gpu_inference_runtime"},
            "boundaries": {"gpu_inference_boundary"},
            "tags": {"gpu", "inference"},
            "clusters": {"gpu_acceleration_stack"},
            "keywords": {"gpu", "utilization", "fallback", "queue"},
            "base_priority": 84,
            "dedupe_group": "gpu_runtime",
            "purpose": "runtime",
            "title": "Inspect live GPU utilization, queue depth, and fallback behavior",
            "why": "GPU-backed latency or failure often comes from oversubscription or silent fallback rather than from the application request shape alone.",
            "action": "Inspect live GPU utilization, queue depth, active workers, fallback behavior, and the concurrency profile during the failing workload.",
            "expected_result": "The intended GPU remains active with stable utilization and no unexpected fallback during the failing workload.",
            "if_failed": "If GPU utilization or fallback behavior is unstable, reduce pressure or correct placement before deeper model tuning.",
            "reference_source_type": "library_docs",
            "reference_hint": "gpu utilization queue fallback verification",
        }
    ],
}

CLUSTER_STEP_TEMPLATES = {
    "auth_identity_flow": [
        {
            "semantic_key": "cluster_auth_flow_alignment",
            "step_family": "cluster.auth.flow_alignment",
            "phase": "secondary_branch_test",
            "domains": {"software"},
            "families": {"authentication", "authorization_policy", "session_identity_boundary"},
            "boundaries": {"browser_boundary", "proxy_boundary", "runtime_boundary"},
            "tags": {"authentication", "authorization", "jwt", "oauth-2.0", "fastapi", "django"},
            "clusters": {"auth_identity_flow"},
            "keywords": {"auth", "session", "identity", "policy"},
            "base_priority": 86,
            "dedupe_group": "auth_cluster",
            "purpose": "secondary",
            "title": "Compare identity propagation, validation, and policy checks across the full auth flow",
            "why": "When several auth signals align, a dedicated flow check is useful to confirm whether the issue sits in issuance, propagation, validation, or policy evaluation.",
            "action": "Walk the captured failing request across issuance, propagation, validation, and policy evaluation to confirm where identity state first diverges from expectations.",
            "expected_result": "The auth flow either remains coherent end to end or the first failing auth stage is isolated.",
            "if_failed": "If one auth stage diverges, fix that stage before broadening the investigation.",
            "reference_source_type": "security_guidance",
            "reference_hint": "identity propagation validation policy flow comparison",
        }
    ],
    "http_proxy_edge": [
        {
            "semantic_key": "cluster_http_edge_alignment",
            "step_family": "cluster.http.edge_alignment",
            "phase": "secondary_branch_test",
            "domains": {"software", "networking"},
            "families": {"cors_proxy_boundary", "http_routing_misconfiguration", "tls_edge_termination"},
            "boundaries": {"browser_boundary", "proxy_boundary", "network_transport_boundary"},
            "tags": {"http", "proxy", "reverse-proxy", "nginx", "apache", "cors"},
            "clusters": {"http_proxy_edge"},
            "keywords": {"origin", "upstream", "edge", "route"},
            "base_priority": 85,
            "dedupe_group": "edge_cluster",
            "purpose": "secondary",
            "title": "Compare browser, edge, and upstream behavior across the full HTTP path",
            "why": "When edge signals compete, an explicit end-to-end HTTP path check is often the most discriminative secondary branch.",
            "action": "Compare the request as seen by the browser, edge layer, and upstream target, focusing on host, origin, path, headers, and timeout behavior across the full HTTP path.",
            "expected_result": "The HTTP path remains coherent end to end or the exact edge divergence point is isolated.",
            "if_failed": "If the path diverges at one edge layer, fix that layer before deeper runtime checks.",
            "reference_source_type": "protocol_reference",
            "reference_hint": "http browser edge upstream path comparison",
        }
    ],
    "container_network_surface": [
        {
            "semantic_key": "cluster_container_surface",
            "step_family": "cluster.container.surface",
            "phase": "secondary_branch_test",
            "domains": {"software", "networking", "ai"},
            "families": {"container_networking", "http_routing_misconfiguration", "dns_service_discovery"},
            "boundaries": {"proxy_boundary", "network_transport_boundary", "deployment_change_hint"},
            "tags": {"docker", "kubernetes", "ingress", "routing", "networking", "dns"},
            "clusters": {"container_network_surface"},
            "keywords": {"service", "selector", "policy", "namespace"},
            "base_priority": 84,
            "dedupe_group": "container_cluster",
            "purpose": "secondary",
            "title": "Validate the live platform path across service discovery, ingress, and network policy",
            "why": "When platform-level tags align, the most useful secondary branch is often the full service-discovery and policy path rather than a single hop check.",
            "action": "Validate service discovery, endpoint registration, ingress mapping, and network policy or security boundaries together across the live platform path.",
            "expected_result": "The platform path is coherent end to end or the first misaligned discovery or policy layer is isolated.",
            "if_failed": "If the platform path is inconsistent, fix that layer before deeper app or model diagnosis.",
            "reference_source_type": "vendor_docs",
            "reference_hint": "platform service discovery ingress policy verification",
        }
    ],
    "model_serving_pipeline": [
        {
            "semantic_key": "cluster_model_serving_pipeline",
            "step_family": "cluster.model.serving_pipeline",
            "phase": "secondary_branch_test",
            "domains": {"ai"},
            "families": {"model_serving_runtime", "retrieval_embeddings_pipeline", "gpu_inference_runtime"},
            "boundaries": {"model_serving_boundary", "database_boundary", "gpu_inference_boundary"},
            "tags": {"model-serving", "inference", "embeddings", "rag", "vector-database"},
            "clusters": {"model_serving_pipeline"},
            "keywords": {"serving", "retrieval", "embedding", "runtime"},
            "base_priority": 86,
            "dedupe_group": "ai_pipeline_cluster",
            "purpose": "secondary",
            "title": "Trace the serving pipeline from request entry through retrieval, model execution, and response assembly",
            "why": "When serving, retrieval, and inference signals align, the strongest secondary branch is often the whole AI pipeline rather than one isolated model call.",
            "action": "Trace the failing AI path from request entry through retrieval, embedding generation, model execution, and response assembly to identify the first inconsistent stage.",
            "expected_result": "The AI pipeline remains coherent end to end or the first inconsistent serving stage is isolated clearly.",
            "if_failed": "If one AI pipeline stage diverges, fix that stage before broadening the search to unrelated infrastructure.",
            "reference_source_type": "library_docs",
            "reference_hint": "ai serving retrieval inference pipeline trace",
        }
    ],
}

__all__ = [
    "DOMAIN_TAGS",
    "PHASE_ORDER",
    "BOUNDARY_LABELS",
    "FAMILY_STEP_SEQUENCE",
    "BASE_STEP_TEMPLATES",
    "FAMILY_STEP_TEMPLATES",
    "BOUNDARY_STEP_TEMPLATES",
    "TAG_STEP_TEMPLATES",
    "CLUSTER_STEP_TEMPLATES",
]
